export type Watches = {
  id: string;
  brand: string;
  model: string;
  price: number;
  type: 'automatic' | 'quartz' | 'mechanical';
  referenceNumber: string;
};

export const watches: Watches[] = [
  {
    id: 'W1',
    brand: 'Rolex',
    model: 'Submariner',
    referenceNumber: '114060',
    price: 8500,
    type: 'automatic',
  },
  {
    id: 'W2',
    brand: 'Omega',
    model: 'Speedmaster',
    referenceNumber: '311.30.42.30.01.005',
    price: 6200,
    type: 'mechanical',
  },
  {
    id: 'W3',
    brand: 'Tag Heuer',
    model: 'Carrera',
    referenceNumber: 'CBM2110.BA0651',
    price: 3100,
    type: 'automatic',
  },
  {
    id: 'W4',
    brand: 'Seiko',
    model: 'Prospex',
    referenceNumber: 'SRP777',
    price: 460,
    type: 'quartz',
  },
  {
    id: 'W5',
    brand: 'Casio',
    model: 'G-Shock',
    referenceNumber: 'GA-2100-1A1',
    price: 120,
    type: 'quartz',
  },
  {
    id: 'W6',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    referenceNumber: '5711/1A-010',
    price: 29000,
    type: 'automatic',
  },
  {
    id: 'W7',
    brand: 'Breitling',
    model: 'Navitimer',
    referenceNumber: 'A17325241B1A1',
    price: 4700,
    type: 'automatic',
  },
  {
    id: 'W8',
    brand: 'Citizen',
    model: 'Eco-Drive',
    referenceNumber: 'BM8180-03E',
    price: 180,
    type: 'quartz',
  },
  {
    id: 'W9',
    brand: 'Rolex',
    model: 'Explorer',
    referenceNumber: '214270',
    price: 8400,
    type: 'mechanical',
  },
  {
    id: 'W10',
    brand: 'Omega',
    model: 'Seamaster',
    referenceNumber: '210.30.42.20.01.001',
    price: 5200,
    type: 'automatic',
  },
  {
    id: 'W11',
    brand: 'Tag Heuer',
    model: 'Aquaracer',
    referenceNumber: 'WAY101A.BA0746',
    price: 2200,
    type: 'quartz',
  },
  {
    id: 'W12',
    brand: 'Seiko',
    model: 'Alpinist',
    referenceNumber: 'SPB121J1',
    price: 700,
    type: 'mechanical',
  },
  {
    id: 'W13',
    brand: 'Casio',
    model: 'Edifice',
    referenceNumber: 'EFV-590D-1AV',
    price: 95,
    type: 'quartz',
  },
  {
    id: 'W14',
    brand: 'Patek Philippe',
    model: 'Aquanaut',
    referenceNumber: '5167A-001',
    price: 28000,
    type: 'automatic',
  },
  {
    id: 'W15',
    brand: 'Breitling',
    model: 'Superocean',
    referenceNumber: 'A17366D81C1S1',
    price: 3500,
    type: 'mechanical',
  },
  {
    id: 'W16',
    brand: 'Citizen',
    model: 'Promaster',
    referenceNumber: 'BN0150-28E',
    price: 300,
    type: 'quartz',
  },
  {
    id: 'W17',
    brand: 'Rolex',
    model: 'Daytona',
    referenceNumber: '116500LN',
    price: 12600,
    type: 'automatic',
  },
  {
    id: 'W18',
    brand: 'Omega',
    model: 'Constellation',
    referenceNumber: '123.10.35.60.02.001',
    price: 4500,
    type: 'quartz',
  },
  {
    id: 'W19',
    brand: 'Tag Heuer',
    model: 'Monaco',
    referenceNumber: 'CAW211P.FC6356',
    price: 4100,
    type: 'automatic',
  },
  {
    id: 'W20',
    brand: 'Seiko',
    model: 'Presage',
    referenceNumber: 'SSA345J1',
    price: 650,
    type: 'mechanical',
  },
  {
    id: 'W21',
    brand: 'Casio',
    model: 'F-91W',
    referenceNumber: 'F91W-1',
    price: 20,
    type: 'quartz',
  },
  {
    id: 'W22',
    brand: 'Patek Philippe',
    model: 'Calatrava',
    referenceNumber: '5227J-001',
    price: 33000,
    type: 'mechanical',
  },
  {
    id: 'W23',
    brand: 'Breitling',
    model: 'Colt',
    referenceNumber: 'A17388101C1A1',
    price: 2700,
    type: 'automatic',
  },
  {
    id: 'W24',
    brand: 'Citizen',
    model: 'Satellite Wave',
    referenceNumber: 'CC9020-54E',
    price: 1100,
    type: 'quartz',
  },
  {
    id: 'W25',
    brand: 'Rolex',
    model: 'Oyster Perpetual',
    referenceNumber: '126000',
    price: 5800,
    type: 'automatic',
  },
  {
    id: 'W26',
    brand: 'Omega',
    model: 'De Ville',
    referenceNumber: '424.10.40.20.03.002',
    price: 3200,
    type: 'automatic',
  },
  {
    id: 'W27',
    brand: 'Tag Heuer',
    model: 'Formula 1',
    referenceNumber: 'WAZ1010.BA0842',
    price: 1500,
    type: 'quartz',
  },
  {
    id: 'W28',
    brand: 'Seiko',
    model: '5 Sports',
    referenceNumber: 'SRPD55',
    price: 200,
    type: 'automatic',
  },
  {
    id: 'W29',
    brand: 'Casio',
    model: 'Pro Trek',
    referenceNumber: 'PRW-3510Y-8CR',
    price: 280,
    type: 'quartz',
  },
  {
    id: 'W30',
    brand: 'Patek Philippe',
    model: 'Complications',
    referenceNumber: '5396R-011',
    price: 60000,
    type: 'mechanical',
  },
  {
    id: 'W31',
    brand: 'Breitling',
    model: 'Avenger',
    referenceNumber: 'A13385101C1A1',
    price: 4500,
    type: 'automatic',
  },
  {
    id: 'W32',
    brand: 'Citizen',
    model: 'Blue Angels',
    referenceNumber: 'AT8020-03L',
    price: 550,
    type: 'quartz',
  },
  {
    id: 'W33',
    brand: 'Rolex',
    model: 'Air-King',
    referenceNumber: '116900',
    price: 7800,
    type: 'automatic',
  },
  {
    id: 'W34',
    brand: 'Omega',
    model: 'Planet Ocean',
    referenceNumber: '215.30.44.21.01.002',
    price: 6600,
    type: 'automatic',
  },
  {
    id: 'W35',
    brand: 'Tag Heuer',
    model: 'Link',
    referenceNumber: 'WBC1319.BA0600',
    price: 2100,
    type: 'quartz',
  },
  {
    id: 'W36',
    brand: 'Seiko',
    model: 'Kinetic',
    referenceNumber: 'SKA371',
    price: 400,
    type: 'quartz',
  },
  {
    id: 'W37',
    brand: 'Casio',
    model: 'Wave Ceptor',
    referenceNumber: 'WVAM640D-1ACR',
    price: 150,
    type: 'quartz',
  },
  {
    id: 'W38',
    brand: 'Patek Philippe',
    model: 'Perpetual Calendar',
    referenceNumber: '5327J-001',
    price: 90000,
    type: 'mechanical',
  },
  {
    id: 'W39',
    brand: 'Breitling',
    model: 'Chronomat',
    referenceNumber: 'AB0110121B1A1',
    price: 7000,
    type: 'automatic',
  },
  {
    id: 'W40',
    brand: 'Citizen',
    model: 'Chronograph',
    referenceNumber: 'CA4210-59E',
    price: 220,
    type: 'quartz',
  },
  {
    id: 'W41',
    brand: 'Rolex',
    model: 'Milgauss',
    referenceNumber: '116400GV',
    price: 8900,
    type: 'automatic',
  },
  {
    id: 'W42',
    brand: 'Omega',
    model: 'Railmaster',
    referenceNumber: '220.12.40.20.01.001',
    price: 5100,
    type: 'mechanical',
  },
  {
    id: 'W43',
    brand: 'Tag Heuer',
    model: 'Autavia',
    referenceNumber: 'CBE2110.BA0687',
    price: 4400,
    type: 'automatic',
  },
  {
    id: 'W44',
    brand: 'Seiko',
    model: 'Astron',
    referenceNumber: 'SSH019',
    price: 2100,
    type: 'quartz',
  },
  {
    id: 'W45',
    brand: 'Casio',
    model: 'Duro',
    referenceNumber: 'MDV106-1AV',
    price: 60,
    type: 'quartz',
  },
  {
    id: 'W46',
    brand: 'Patek Philippe',
    model: 'World Time',
    referenceNumber: '5230R-001',
    price: 55000,
    type: 'mechanical',
  },
  {
    id: 'W47',
    brand: 'Breitling',
    model: 'Superocean Heritage',
    referenceNumber: 'A13313121B1X1',
    price: 3800,
    type: 'automatic',
  },
  {
    id: 'W48',
    brand: 'Citizen',
    model: 'Nighthawk',
    referenceNumber: 'BJ7000-52E',
    price: 290,
    type: 'quartz',
  },
  {
    id: 'W49',
    brand: 'Rolex',
    model: 'Yacht-Master',
    referenceNumber: '126622',
    price: 11600,
    type: 'automatic',
  },
  {
    id: 'W50',
    brand: 'Omega',
    model: 'Globemaster',
    referenceNumber: '130.33.39.21.03.001',
    price: 6200,
    type: 'automatic',
  },
];
